### ISSUE TITLE
Beacon

### ISSUE THREAD

**Issue by lp74** [reelyactive/web-ble-demo#1]
I am trying the demo on MAC OSX
I have activated the flags, checked the chrome://bluetooth-internals/#adapter and installed BeaconScope to broadcast ads through my smartphone.

The demo starts and I grant permission but nothing is discovered.

May you provide some extra information?

**Comment by jeffyactive** [comment]
Web Bluetooth Scanning is an **experimental** feature, which we've only observed running reliably on Chrome on Android.  We have observed Chrome on desktop appear to initiate Web Bluetooth Scanning (no errors thrown) but then not detect any devices.  It seems this is consistent with your experience.

Give it a try in Chrome on Android if you can.  We've found that when it works, it works surprisingly well: https://youtu.be/Pa4EpT00cug

See also this guide: https://reelyactive.github.io/pareto-anywhere/enable-web-bluetooth-scanning/

Hope that's helpful.  Kindly close the issue if there are no other questions.  Happy scanning!

**Comment by lp74** [comment]
Thank you.
